# https://taskfile.dev

version: '3'

output: prefixed

vars:
  Name: yomo
  ExeName: yomo{{exeExt}}
  ExeDir: yomo 
  ReleaseDir: release 
  Version: 
    sh: git describe --always --tags --dirty
  Date:
    sh: git show -s --format=%cs {{.Commit}}
  Commit:
    sh: git rev-parse --short HEAD
  Module:
    sh: go list -m

tasks:
  default:
    cmds:
      - task -l 
    silent: true

  build:
    desc: build yomo cli tools
    cmds:
      - echo "{{.Name}} building..."
      - go build -v -o {{.ExeDir}}/{{.ExeName}} -ldflags "-s -w -X {{.Module}}/cmd.Version={{.Version}} -X {{.Module}}/cmd.Date={{.Date}}" {{.ExeDir}}/main.go
      - echo "{{.Name}} built."
    generates:
      - "{{.ExeDir}}/{{.ExeName}}"
    sources:
      - "**/*.go"
    method: none
    silent: true

  install:
    desc: install yomo cli tools
    deps: []
    dir: yomo
    cmds:
      - echo "{{.Name}} install..."
      - go install -ldflags "-s -w -X {{.Module}}/cmd.Version={{.Version}} -X {{.Module}}/cmd.Date={{.Date}}" 
      - echo "{{.Name}} {{.Version}}({{.Date}}) is installed."
    silent: true

  release:
    desc: release yomo cli tools
    cmds:
      - echo "{{.Name}} release..."
      - GOOS=darwin GOARCH=amd64 go build -ldflags "-w -s -X {{.Module}}/cmd.Version={{.Version}} -X {{.Module}}/cmd.Date={{.Date}}" -o {{.ReleaseDir}}/{{.Name}}_{{.Version}}_mac yomo/main.go
      - GOOS=linux GOARCH=amd64 go build -ldflags "-w -s -X {{.Module}}/cmd.Version={{.Version}} -X {{.Module}}/cmd.Date={{.Date}}" -o {{.ReleaseDir}}/{{.Name}}_{{.Version}}_linux yomo/main.go
      - GOOS=windows GOARCH=amd64 go build -ldflags "-w -s -X {{.Module}}/cmd.Version={{.Version}} -X {{.Module}}/cmd.Date={{.Date}}" -o {{.ReleaseDir}}/{{.Name}}_{{.Version}}_windows.exe yomo/main.go
      - echo "{{.Name}} {{.Version}} is released."
    silent: true

  run:
    desc: run yomo cli 
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}}"
    silent: false

  example:
    desc: example
    deps: [example-yomo-server,example-source,example-stream-fn,example-connector]
    cmds:
      - echo "example"

  example-yomo-dev:
    desc: "run stream function via yomo-dev"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} dev -m example/go.mod example/stream-fn/app.go"
    silent: false

  example-source:
    desc: run source application
    deps: [example-source-build]
    dir: "example/source"
    cmds:
      - "./source{{exeExt}}"
    silent: false

  example-source-build:
    desc: build source application
    dir: "example/source"
    cmds:
      - echo "source building..."
      - "go build -o source{{exeExt}} main.go"
      - echo "source built."
    silent: false

  example-stream-fn:
    desc: "run stream function"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} run -n Noise -m example/go.mod example/stream-fn/app.go"
    silent: false

  example-yomo-server:
    desc: "run yomo-server"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} serve -c example/yomo-server/workflow.yaml"
    silent: false

  example-connector:
    desc: run output connector
    deps: [example-connector-build]
    dir: "example/connector"
    cmds:
      - echo "Output Connector building..."
      - "./connector{{exeExt}}"
      - echo "connector built."
    silent: false

  example-connector-build:
    desc: build output connector
    dir: "example/connector"
    cmds:
      - "go build -o connector{{exeExt}} main.go"
    silent: false

  version:
    desc: "print version"
    cmds: 
      - echo "Version {{.Version}}({{.Date}})"
    silent: true

  clean:
    desc: "clean"
    cmds: 
      - echo 'cleaning...'
      - rm -rf ./example/source/source{{exeExt}}
      - rm -rf ./example/stream-fn/sl.*
      - rm -rf ./example/connector/connector{{exeExt}}
      - rm -rf ./yomo/yomo{{exeExt}}
      - rm -rf ./release
      - echo 'clean.'
    silent: true

  example-mesh-us:
    desc: example-mesh-us
    deps: [example-mesh-yomo-server-us,example-mesh-stream-fn-us,example-mesh-connector-us,example-mesh-source-us]
    cmds:
      - echo "example-mesh-us"

  example-mesh-eu:
    desc: example-mesh-eu
    deps: [example-mesh-yomo-server-eu,example-mesh-stream-fn-eu,example-mesh-connector-eu,example-mesh-source-eu]
    cmds:
      - echo "example-mesh-eu"

  example-mesh-yomo-server-us:
    desc: "run yomo-server-us"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} serve -c example/mesh/us/workflow.yaml -m https://mesh-config.yomo.run/api/configs"
    silent: false

  example-mesh-yomo-server-eu:
    desc: "run yomo-server-eu"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} serve -c example/mesh/eu/workflow.yaml -m https://mesh-config.yomo.run/api/configs"
    silent: false

  example-mesh-source-us:
    desc: run source application
    deps: [example-mesh-source-build]
    dir: "example/mesh/source"
    cmds:
      - "./source{{exeExt}}"
    env:
      PORT: 9000
    silent: false

  example-mesh-source-eu:
    desc: run source application
    deps: [example-mesh-source-build]
    dir: "example/mesh/source"
    cmds:
      - "./source{{exeExt}}"
    env:
      PORT: 9800
    silent: false

  example-mesh-source-build:
    desc: build source application
    dir: "example/mesh/source"
    cmds:
      - echo "source building..."
      - "go build -o source{{exeExt}} main.go"
      - echo "source built."
    silent: false

  example-mesh-stream-fn-us:
    desc: run stream function
    deps: [example-mesh-stream-fn-build]
    dir: "example/mesh/stream-fn"
    cmds:
      - "./stream-fn{{exeExt}}"
    env:
      PORT: 9000
      REGION: "💖 US 💖"
    silent: false

  example-mesh-stream-fn-eu:
    desc: run stream function
    deps: [example-mesh-stream-fn-build]
    dir: "example/mesh/stream-fn"
    cmds:
      - "./stream-fn{{exeExt}}"
    env:
      PORT: 9800
      REGION: "💙 EU 💙"
    silent: false

  example-mesh-stream-fn-build:
    desc: build stream function
    dir: "example/mesh/stream-fn"
    cmds:
      - "go build -o stream-fn{{exeExt}} app.go"
    silent: false

  example-mesh-connector-us:
    desc: run output connector
    deps: [example-mesh-connector-build]
    dir: "example/mesh/connector"
    cmds:
      - "./connector{{exeExt}}"
    env:
      PORT: 9000
    silent: false

  example-mesh-connector-eu:
    desc: run output connector
    deps: [example-mesh-connector-build]
    dir: "example/mesh/connector"
    cmds:
      - "./connector{{exeExt}}"
    env:
      PORT: 9800
    silent: false

  example-mesh-connector-build:
    desc: build output connector
    dir: "example/mesh/connector"
    cmds:
      - "go build -o connector{{exeExt}} main.go"
    silent: false
